### ISSUE TITLE
传过来的声音像是磁带听歌快没电了的那个样子怎么回事

### ISSUE THREAD

**Issue by zz99906** [flben233/TyuShare#5]
如题

**Comment by zz99906** [comment]
失真严重，有延时

**Comment by flben233** [comment]
这个问题前段时间也有人说过，我怀疑可能是cpu太忙导致的采集的声音不连续，也有可能是网络问题导致的丢包，总之看来这个自己写的串流模块还得优化一下。。。先退回上个版本吧

**Comment by zz99906** [comment]
这里报告，可能是网络丢包，cpu应该没啥问题，我这2颗E5  128内存都是卡

**Comment by flben233** [comment]
两台电脑之间都是wifi吗？连的是路由器还是光猫？

**Comment by zz99906** [comment]
一个有限，一个无限

**Comment by zz99906** [comment]
有wx吗，可以加一下方便沟通

**Comment by flben233** [comment]
qq2541028866，wx不咋用
